@url=http://localhost:3000

### Listado de productos
GET {{url}}/productos

### Detalles de producto
GET {{url}}/productos/3

### Crear producto
POST {{url}}/productos
Content-Type: application/json

{
    "nombre": "Pomelo",
    "cantidad": 11
}

### Modificar producto
PUT {{url}}/productos/5
Content-Type: application/json

{
  "nombre": "Jaboooooon",
  "cantidad": 30
}

### Quitar producto
DELETE {{url}}/productos/7

### Agregar otro producto

POST {{url}}/productos
content-type: application/json

{
  "nombre": "Huevos",
  "cantidad": 3
}

### 

GET {{url}}/productos

### Agregar otro producto PERO con id 3 (no se puede, por defecto se crea con id autoincremental)

POST {{url}}/productos
content-type: application/json

{
  "nombre": "Carne",
  "cantidad": 10
}



###
DELETE {{url}}/productos/9
### 
GET {{url}}/productos